version: '3.1'

services:
  # Databases # #
  db:
    image: mysql
    container_name: database-nlw
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: nlw
      MYSQL_USER: docker
    ports:
      - 3306:3306

  # APP # #
  app:
    container_name: app-nlw
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
